builders:
  yaroorm_generator:
    import: "package:yaroorm/builder.dart"
    builder_factories: ["yaroormBuilder"]
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
