name: yaroodev

packages:
  - yaroo
  - yaroorm

command:
  version:
    branch: master
    workspaceChangelog: true

  bootstrap:
    runPubGetInParallel: false

scripts:
  tests:
    run: |
      melos exec -c 1  -- "dart test ." --fail-fast
    description: Run all static analysis checks.

  format: melos exec -- "dart format . --line-length=120"
  analyze: melos exec -- "dart analyze . --fatal-infos"
