name: yaroodev

packages:
  - yaroo
  - yaroorm

command:
  version:
    branch: master
    workspaceChangelog: true

  bootstrap:
    runPubGetInParallel: false

scripts:
  tests:
    run: |
      melos exec -c 1  -- "dart test ." --fail-fast
    description: Run all static analysis checks.

  analyze:
    run: |
      melos exec -c 1 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.
