name: yaroorm
description: Easy migrations, query-builder & ORM for Postgres, SQLite, MySQL & MariaDB.
version: 0.0.3+2
homepage: https://docs.yaroo.dev/orm/quickstart
repository: https://github.com/codekeyz/yaroo

topics:
  - yaroo
  - postgres
  - mariadb
  - mysql
  - sqlite

environment:
  sdk: ^3.3.1

dependencies:
  sqflite_common_ffi: ^2.3.3+1
  sqflite_common: ^2.5.4+4
  mysql_client: ^0.0.27
  postgres: ^3.4.0

  meta: ^1.11.0
  grammer: ^1.0.3
  recase: ^4.1.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  melos: ^6.2.0
  test: ^1.24.0
