name: yaroo_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  cli_completion: ^0.4.0
  collection: ^1.18.0
  meta: ^1.11.0
  path: ^1.9.0
  yaroorm:
  mason_logger: ^0.2.11

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
  build_runner:
  yaroorm_builder:

executables:
  yaroo:
