name: orm-docker
version: "3.8"

services:
  maria_db:
    container_name: mariadb
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: test_db
      MARIADB_USER: tester
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3000:3306"
    volumes:
      - mariadb_data:/var/lib/mariadb/data

volumes:
  mariadb_data: