name: orm-docker
version: "3.8"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: test_db
      MARIADB_USER: tester
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3000:3306"
    volumes:
      - mariadb_data:/var/lib/mariadb/data
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_USER: 'tester'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3001:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql_random/data


volumes:
  mariadb_data:
  mysqldb_data: