name: yaroo_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  cli_completion: ^0.4.0
  cli_util: ^0.4.1
  collection: ^1.18.0
  mason_logger: ^0.2.11
  meta: ^1.11.0
  path: ^1.9.0
  yaroorm:

dev_dependencies:
  build_runner: ^2.4.7
  test: ^1.24.0
  lints:

executables:
  yaroo:
