name: yaroo_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  cli_completion: ^0.4.0
  collection: ^1.18.0
  meta: ^1.11.0
  path: ^1.9.0
  yaroorm:
  mason_logger: ^0.2.11

  analyzer:
  code_builder: ^4.10.0
  dart_style:
  source_gen: ^1.5.0
  grammer: ^1.0.3
  recase: ^4.1.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

executables:
  yaroo:
