name: yaroorm_tests
description: Tests for yaroorm
version: 0.0.1

# publish_to: none

environment:
  sdk: ^3.5.0-152.0.dev

dependencies:
  collection: ^1.18.0
  macros: ^0.1.0-main.5
  uuid: ^4.4.0
  yaroorm:
    git:
      url: https://github.com/codekeyz/yaroorm.git
      ref: feat/maybe-macros

dev_dependencies:
  lints:
  build_runner: ^2.4.9
  test: ^1.25.5
