name: yaroo
description: Unleash the Full Power of Dart in Backend Development.
version: 0.0.1
repository: https://github.com/codekeyz/yaroo.git

publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  pharaoh:
    git:
      url: https://github.com/codekeyz/pharaoh.git
      path: packages/pharaoh
  spanner: ^1.0.1+2
  spookie: ^1.0.2+1
  meta: ^1.11.0
  grammer: ^1.0.3
  collection: ^1.18.0
  dotenv: ^4.2.0
  get_it: ^7.6.4
  uuid: ^4.2.1

  # build related
  build_runner: any
  reflectable:
    git:
      url: https://github.com/codekeyz/reflectable.dart.git
      path: reflectable

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
