name: yaroorm_test
description: Tests for yaroorm
version: 0.0.1

publish_to: none

environment:
  sdk: ^3.3.1

dependencies:
  uuid: ^4.4.0
  yaroorm:
    path: '../'

dev_dependencies:
  test: ^1.25.8
  collection: ^1.19.1
  build_runner: ^2.4.9
  yaroorm_cli: 
    path: '../yaroorm_cli'