name: yaroorm_builder
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: '>=5.13.0 <7.0.0'
  code_builder: ^4.10.0
  source_gen: ^1.5.0
  dart_style:
  build: ^2.3.1
  yaroorm:
  recase: ^4.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
