name: yaroorm_cli
description: A starting point for Dart libraries or applications.
version: 0.0.3+1
homepage: https://docs.yaroo.dev/orm/quickstart
repository: https://github.com/codekeyz/yaroo

environment:
  sdk: ^3.3.1

dependencies:
  # Code-Gen
  analyzer: ^6.8.0
  code_builder: ^4.10.0
  source_gen: ^1.5.0
  dart_style: ^2.3.0
  build: ^2.3.1
  
  # CLI
  args: ^2.4.2
  path: ^1.9.0
  crypto: ^3.0.3
  recase: ^4.1.0
  grammer: ^1.0.3
  yaroorm: ^0.0.3
  cli_table: ^1.0.2
  collection: ^1.19.1
  mason_logger: ^0.3.1
  cli_completion: ^0.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  yaroorm: yaroorm_cli
