name: yaroorm
description: Easy migrations, query-builder & ORM for Postgres, SQLite, MySQL & MariaDB.
version: 0.0.1

topics:
  - yaroo
  - orm
  - postgres
  - mariadb
  - mysql
  - sqlite

environment:
  sdk: ^3.0.0

dependencies:
  sqflite_common_ffi: ^2.3.2
  sqflite_common: ^2.3.2
  mysql_client: ^0.0.27
  postgres: ^3.0.4

  meta: ^1.11.0
  collection: ^1.18.0
  grammer: ^1.0.3
  recase: ^4.1.0
  reflectable:
    git:
      url: https://github.com/codekeyz/reflectable.dart.git
      path: reflectable

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  yaroo_cli:
    git:
      url: https://github.com/codekeyz/yaroo.git
      path: packages/yaroo_cli
  path: ^1.9.0
