# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1.3
      - uses: bluefireteam/melos-action@v3

      - name: Bootstrap
        run: |
          dart pub global activate melos
          melos bootstrap


      - name: Check formatting
        run: melos format -- --set-exit-if-changed

      - name: Check linting
        run: |
          melos exec -- "dart run build_runner build"
          melos analyze

  test:
    name: Test Packages
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
          MARIADB_DATABASE: mariadb_test_db
          MARIADB_USER: tester
          MARIADB_PASSWORD: password
        ports:
          - 3306:3306
      mysql:
        image: mysql
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mysql_test_db
          MYSQL_USER: tester
          MYSQL_PASSWORD: password
        ports:
          - 3307:3306

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1.3
      - uses: bluefireteam/melos-action@v3

      - name: Prepare Workspace
        run: |
          dart pub global activate melos
          dart pub global activate coverage
          melos bootstrap
          melos exec -- "dart run build_runner build"

      #      - name: Run Unit Tests
      #        run: melos tests:ci

      - name: Run E2E Tests
        run: |
          cd yaroorm
          sudo mysql -e "ALTER USER 'tester'@'localhost' IDENTIFIED BY 'password'; FLUSH PRIVILEGES;"
          dart test test/integration/mariadb.e2e.dart
      #          dart test test/integration/mysql.e2e.dart

      #          cd yaroorm && "./e2e_test.sh"

      - name: Combine Coverage
        run: melos coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage/*_lcov.info